services:
  web:
    image: nginx:alpine
    # image: webslab/impulsa:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.template.conf:/etc/nginx/templates/10-variables.conf.template:ro
      # prod:
      # - ./dist/base:/var/www/html/base
      # - ./dist:/var/www/html
      # dev:
      - ./public:/var/www/html
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 8000
      FILE_HOST: 127.0.0.1
      FILE_PORT: 9000

  php-fpm:
    image: webslab/filefind:latest
    network_mode: service:web
    volumes:
      # prod:
      # - ./dist:/app/resources
      # dev: ⬇️
      - ./public:/app/resources

  surrealdb:
    image: surrealdb/surrealdb:v2.2.0
    # image: webslab/store-demo:latest
    network_mode: service:web
    command:
      - start
      - memory
      - -A
      - --no-banner
      # - --log=trace
      # - --log=info
      - --user=root
      - --pass=root
      # - --bind=0.0.0.0:8000
